language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    sudo apt-get update -qq
    sudo apt-get install -y cmake
  fi
install:
  - mkdir build
  - cd build
  - cmake ..
  - make
script: true
